version: '3'
services:
  app:
    build:
      context: ./docker
      dockerfile: app_dockerfile
    container_name: demo-symfony-app
    volumes:
      - ./:/var/www/html
    command: bash -c "composer install & php-fpm"
    depends_on:
      - db
  web:
    image: nginx:alpine
    container_name: demo-symfony-web
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    depends_on:
      - app
  db:
    image: postgres:16-alpine
    container_name: demo-symfony-db
    environment:
      POSTGRES_DB: example
      POSTGRES_PASSWORD: example
      POSTGRES_USER: example
  adminer:
    image: dockette/adminer:postgres
    container_name: demo-symfony-adminer
    ports:
      - "8080:80"
